### ISSUE TITLE
Learn To Code with JavaScript (javascript) Track edits

### ISSUE THREAD

**Issue by Habenzy** [BurlingtonCodeAcademy/codelikethis#69]
Lessons in the Track:
  * regexp.md (Regular Expressions) -suggested we expand into brief slide deck
  * tdd_in_js (TDD in JS) -suggest we remove completely, already getting test driven from 'agile'
  * ecosystem -empty; suggest we remove it 
  * es6 -empty; suggest we remove it
  * promises -empty; suggest we combine with async/await as new 'asynchronous JS' lesson
  * async/await -see above
  * Rest and spread -empty; delete
  * named params -empty; delete?
  * javascript for programmers -redundant; delete
  * functional programming -empty, probably doesn't need it's own lesson; delete

Lessons imported from other Tracks:
  * from server_side_js: hello_express; -remove from javascript.rb track
  * from tricks_of_the_trade: debbuging, modern debugging; -combine, and move into javascript
  * from agile: test_driven; -remove from javascript.rb track

**Comment by Dangeranger** [comment]
@Habenzy Let's do these in this order:
- [ ] Combine Promises and Async/Await into an Asynchronous lesson
- [ ] Create a Debugging in JavasScript lesson, with `console.log()`, browser tools, and VS Code.
- [ ] Remove the following: 
  - [ ] Ecosystem
  - [ ] Tdd_in_js
  - [ ] ES6
  - [ ] Rest and Spread
  - [ ] Named Params
  - [ ] JavaScript for programmers
  - [ ] Functional Programming
- [ ] Create a rough outline of a Testing in JavaScript using Mocha/Chai or Jest, maybe both.

I think we need to leave the `Hello Express` in both tracks so that if someone visits the Server Side Programming track only, they are not completely lost. I can see how you thought it was weird for them though.
